@startuml
left to right direction
actor Cliente

rectangle "Identidad y Acceso" {
  usecase "Registrarse" as UC1
  usecase "Iniciar Sesión" as UC2
  usecase "Recuperar Contraseña" as UC3
  usecase "Gestionar Perfil" as UC4
}

rectangle "Pagos" {
  usecase "Realizar Pago" as UC5
  usecase "Ver Historial de Pagos" as UC6
}

Cliente --> UC1
Cliente --> UC2
Cliente --> UC3
Cliente --> UC4
Cliente --> UC5
Cliente --> UC6
@enduml
