@startuml
left to right direction
actor "Abogado Principal" as Abogado
actor "Abogado Asistente" as Asistente

rectangle "Comunicación" {
  usecase "Chat con Cliente" as UC1
  usecase "Solicitar Videollamada" as UC2
  usecase "Recibir Notificaciones" as UC3
}

Abogado --> UC1
Abogado --> UC2
Abogado --> UC3
Asistente --> UC1
Asistente --> UC3
@enduml
