@startuml
left to right direction
actor Administrador

rectangle "Gestión de Clientes" {
  usecase "Registrar Cliente" as UC1
  usecase "Editar Cliente" as UC2
  usecase "Eliminar Cliente" as UC3
  usecase "Consultar Cliente" as UC4
}

Administrador --> UC1
Administrador --> UC2
Administrador --> UC3
Administrador --> UC4
@enduml
